services:
  traefik:
    image: "traefik:v3.1"
    container_name: traefik
    networks:
      - cloudcrafter
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  postgres:
    image: postgres:16-alpine
    networks:
      - cloudcrafter
    environment:
      POSTGRES_USER: cloudcrafter
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudcrafter
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    networks:
      - cloudcrafter
    ports:
      - '6379:6379'
  
  redis-testing:
    image: redis:alpine
    networks:
      - cloudcrafter
    ports:
      - '6380:6379'



networks:
  cloudcrafter:
    name: cloudcrafter
    driver: bridge
    external: true
volumes:
  pgdata:
    driver: local
  pgdata-testing:
    driver: local
  testhostdata:
    driver: local
  stats_db:
    driver: local
