import { generate } from 'orval'

export default async function generateClient({url, outputPath}: {url: string, outputPath: string}) {
    await generate({
        input: url,
        output: {
            target: outputPath,
            client: 'react-query',
            prettier: true,
            override: {
                query: {
                    useSuspenseQuery: true
                },
                header: info => [
                    `Generated by orval 🍺`,
                    `Do not edit manually.`,
                    ...(info.title ? [info.title] : []),
                    ...(info.description ? [info.description] : []),
                    ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
                ],

                mutator: {
                    path: './src/utils/axios-instance.ts',
                    name: 'axiosInstance',
                },
            }
        }
    })


    return {
        success: true
    }
}
