import orval from 'orval'

export default async function generate({url, outputPath}: {url: string, outputPath: string}) {
  await orval({
    input: url,
    output: {
      target: outputPath,
      client: 'react-query',
      prettier: true,
      override: {
        query: {
          useSuspenseQuery: true
        },
        header: info => [
          'eslint-disable @nx/enforce-module-boundaries',
          `Generated by orval 🍺`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],

        mutator: {
          path: './axios-instance.ts',
          name: 'axiosInstance',
        },
      }
    }
  })

  return {
    success: true
  }
}
